name: BetterMobsOverworld
version: 1.0.0
main: MadoxMc\Mobs\Main
api: 5.0.0
author: MadoxMc
commands:
  killmobs:
    usage: "/killmobs"
    description: "Kill all Mobs"
    permission: mobs.operator
  listmobs:
    usage: "/listmobs"
    description: "List all Mobs"
    permission: mobs.operator
  summon:
    usage: "/summon <type> [quantity]"
    description: "Summon a Mob"
    permission: mobs.operator
permissions:
  mobs.operator:
    description: allow using mob commands
    default: op
